# permissions for end users to view minios.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: minio-viewer-role
rules:
- apiGroups:
  - pipecd.kanatakita.com
  resources:
  - minios
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - pipecd.kanatakita.com
  resources:
  - minios/status
  verbs:
  - get
