# permissions for end users to edit minios.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: minio-editor-role
rules:
- apiGroups:
  - pipecd.kanatakita.com
  resources:
  - minios
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pipecd.kanatakita.com
  resources:
  - minios/status
  verbs:
  - get
