# permissions for end users to view pipeds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: piped-viewer-role
rules:
- apiGroups:
  - pipecd.kanatakita.com
  resources:
  - pipeds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - pipecd.kanatakita.com
  resources:
  - pipeds/status
  verbs:
  - get
