---
apiVersion: v1
kind: Secret
metadata:
  name: secret-sample
data:
  encryption-key: "ZW5jcnlwdGlvbi1rZXktanVzdC11c2VkLWZvci1xdWlja3N0YXJ0"  # -> encryption-key-just-used-for-quickstart
  minio-access-key: "cXVpY2tzdGFydC1hY2Nlc3Mta2V5"  # -> quickstart-access-key
  minio-secret-key: "cXVpY2tzdGFydC1zZWNyZXQta2V5"  # -> quickstart-access-key
