// +build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnalysisProviderDatadogConfig) DeepCopyInto(out *AnalysisProviderDatadogConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnalysisProviderDatadogConfig.
func (in *AnalysisProviderDatadogConfig) DeepCopy() *AnalysisProviderDatadogConfig {
	if in == nil {
		return nil
	}
	out := new(AnalysisProviderDatadogConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnalysisProviderPrometheusConfig) DeepCopyInto(out *AnalysisProviderPrometheusConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnalysisProviderPrometheusConfig.
func (in *AnalysisProviderPrometheusConfig) DeepCopy() *AnalysisProviderPrometheusConfig {
	if in == nil {
		return nil
	}
	out := new(AnalysisProviderPrometheusConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnalysisProviderStackdriverConfig) DeepCopyInto(out *AnalysisProviderStackdriverConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnalysisProviderStackdriverConfig.
func (in *AnalysisProviderStackdriverConfig) DeepCopy() *AnalysisProviderStackdriverConfig {
	if in == nil {
		return nil
	}
	out := new(AnalysisProviderStackdriverConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudProviderCloudRunConfig) DeepCopyInto(out *CloudProviderCloudRunConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudProviderCloudRunConfig.
func (in *CloudProviderCloudRunConfig) DeepCopy() *CloudProviderCloudRunConfig {
	if in == nil {
		return nil
	}
	out := new(CloudProviderCloudRunConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudProviderKubernetesConfig) DeepCopyInto(out *CloudProviderKubernetesConfig) {
	*out = *in
	in.AppStateInformer.DeepCopyInto(&out.AppStateInformer)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudProviderKubernetesConfig.
func (in *CloudProviderKubernetesConfig) DeepCopy() *CloudProviderKubernetesConfig {
	if in == nil {
		return nil
	}
	out := new(CloudProviderKubernetesConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudProviderLambdaConfig) DeepCopyInto(out *CloudProviderLambdaConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudProviderLambdaConfig.
func (in *CloudProviderLambdaConfig) DeepCopy() *CloudProviderLambdaConfig {
	if in == nil {
		return nil
	}
	out := new(CloudProviderLambdaConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudProviderTerraformConfig) DeepCopyInto(out *CloudProviderTerraformConfig) {
	*out = *in
	if in.Vars != nil {
		in, out := &in.Vars, &out.Vars
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudProviderTerraformConfig.
func (in *CloudProviderTerraformConfig) DeepCopy() *CloudProviderTerraformConfig {
	if in == nil {
		return nil
	}
	out := new(CloudProviderTerraformConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlPlane) DeepCopyInto(out *ControlPlane) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlPlane.
func (in *ControlPlane) DeepCopy() *ControlPlane {
	if in == nil {
		return nil
	}
	out := new(ControlPlane)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ControlPlane) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlPlaneCache) DeepCopyInto(out *ControlPlaneCache) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlPlaneCache.
func (in *ControlPlaneCache) DeepCopy() *ControlPlaneCache {
	if in == nil {
		return nil
	}
	out := new(ControlPlaneCache)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlPlaneConfig) DeepCopyInto(out *ControlPlaneConfig) {
	*out = *in
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlPlaneConfig.
func (in *ControlPlaneConfig) DeepCopy() *ControlPlaneConfig {
	if in == nil {
		return nil
	}
	out := new(ControlPlaneConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlPlaneConfigSpec) DeepCopyInto(out *ControlPlaneConfigSpec) {
	*out = *in
	in.Datastore.DeepCopyInto(&out.Datastore)
	in.Filestore.DeepCopyInto(&out.Filestore)
	out.Cache = in.Cache
	if in.Projects != nil {
		in, out := &in.Projects, &out.Projects
		*out = make([]ControlPlaneProject, len(*in))
		copy(*out, *in)
	}
	if in.SharedSSOConfigs != nil {
		in, out := &in.SharedSSOConfigs, &out.SharedSSOConfigs
		*out = make([]SharedSSOConfig, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlPlaneConfigSpec.
func (in *ControlPlaneConfigSpec) DeepCopy() *ControlPlaneConfigSpec {
	if in == nil {
		return nil
	}
	out := new(ControlPlaneConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlPlaneDataStore) DeepCopyInto(out *ControlPlaneDataStore) {
	*out = *in
	if in.FirestoreConfig != nil {
		in, out := &in.FirestoreConfig, &out.FirestoreConfig
		*out = new(DataStoreFireStoreConfig)
		**out = **in
	}
	if in.DynamoDBConfig != nil {
		in, out := &in.DynamoDBConfig, &out.DynamoDBConfig
		*out = new(DataStoreDynamoDBConfig)
		**out = **in
	}
	if in.MongoDBConfig != nil {
		in, out := &in.MongoDBConfig, &out.MongoDBConfig
		*out = new(DataStoreMongoDBConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlPlaneDataStore.
func (in *ControlPlaneDataStore) DeepCopy() *ControlPlaneDataStore {
	if in == nil {
		return nil
	}
	out := new(ControlPlaneDataStore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlPlaneFileStore) DeepCopyInto(out *ControlPlaneFileStore) {
	*out = *in
	if in.GCSConfig != nil {
		in, out := &in.GCSConfig, &out.GCSConfig
		*out = new(FileStoreGCSConfig)
		**out = **in
	}
	if in.S3Config != nil {
		in, out := &in.S3Config, &out.S3Config
		*out = new(FileStoreS3Config)
		**out = **in
	}
	if in.MinioConfig != nil {
		in, out := &in.MinioConfig, &out.MinioConfig
		*out = new(FileStoreMinioConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlPlaneFileStore.
func (in *ControlPlaneFileStore) DeepCopy() *ControlPlaneFileStore {
	if in == nil {
		return nil
	}
	out := new(ControlPlaneFileStore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlPlaneList) DeepCopyInto(out *ControlPlaneList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ControlPlane, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlPlaneList.
func (in *ControlPlaneList) DeepCopy() *ControlPlaneList {
	if in == nil {
		return nil
	}
	out := new(ControlPlaneList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ControlPlaneList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlPlaneProject) DeepCopyInto(out *ControlPlaneProject) {
	*out = *in
	out.StaticAdmin = in.StaticAdmin
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlPlaneProject.
func (in *ControlPlaneProject) DeepCopy() *ControlPlaneProject {
	if in == nil {
		return nil
	}
	out := new(ControlPlaneProject)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlPlaneSpec) DeepCopyInto(out *ControlPlaneSpec) {
	*out = *in
	if in.ReplicasGateway != nil {
		in, out := &in.ReplicasGateway, &out.ReplicasGateway
		*out = new(int32)
		**out = **in
	}
	if in.ReplicasServer != nil {
		in, out := &in.ReplicasServer, &out.ReplicasServer
		*out = new(int32)
		**out = **in
	}
	if in.ReplicasCache != nil {
		in, out := &in.ReplicasCache, &out.ReplicasCache
		*out = new(int32)
		**out = **in
	}
	if in.ReplicasOps != nil {
		in, out := &in.ReplicasOps, &out.ReplicasOps
		*out = new(int32)
		**out = **in
	}
	if in.Secret != nil {
		in, out := &in.Secret, &out.Secret
		*out = new(v1.SecretVolumeSource)
		(*in).DeepCopyInto(*out)
	}
	in.Config.DeepCopyInto(&out.Config)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlPlaneSpec.
func (in *ControlPlaneSpec) DeepCopy() *ControlPlaneSpec {
	if in == nil {
		return nil
	}
	out := new(ControlPlaneSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlPlaneStatus) DeepCopyInto(out *ControlPlaneStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlPlaneStatus.
func (in *ControlPlaneStatus) DeepCopy() *ControlPlaneStatus {
	if in == nil {
		return nil
	}
	out := new(ControlPlaneStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataStoreDynamoDBConfig) DeepCopyInto(out *DataStoreDynamoDBConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataStoreDynamoDBConfig.
func (in *DataStoreDynamoDBConfig) DeepCopy() *DataStoreDynamoDBConfig {
	if in == nil {
		return nil
	}
	out := new(DataStoreDynamoDBConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataStoreFireStoreConfig) DeepCopyInto(out *DataStoreFireStoreConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataStoreFireStoreConfig.
func (in *DataStoreFireStoreConfig) DeepCopy() *DataStoreFireStoreConfig {
	if in == nil {
		return nil
	}
	out := new(DataStoreFireStoreConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataStoreMongoDBConfig) DeepCopyInto(out *DataStoreMongoDBConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataStoreMongoDBConfig.
func (in *DataStoreMongoDBConfig) DeepCopy() *DataStoreMongoDBConfig {
	if in == nil {
		return nil
	}
	out := new(DataStoreMongoDBConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EmbeddedPersistentVolumeClaim) DeepCopyInto(out *EmbeddedPersistentVolumeClaim) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EmbeddedPersistentVolumeClaim.
func (in *EmbeddedPersistentVolumeClaim) DeepCopy() *EmbeddedPersistentVolumeClaim {
	if in == nil {
		return nil
	}
	out := new(EmbeddedPersistentVolumeClaim)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EmbeddedSecretKeySelector) DeepCopyInto(out *EmbeddedSecretKeySelector) {
	*out = *in
	if in.Optional != nil {
		in, out := &in.Optional, &out.Optional
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EmbeddedSecretKeySelector.
func (in *EmbeddedSecretKeySelector) DeepCopy() *EmbeddedSecretKeySelector {
	if in == nil {
		return nil
	}
	out := new(EmbeddedSecretKeySelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Environment) DeepCopyInto(out *Environment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Environment.
func (in *Environment) DeepCopy() *Environment {
	if in == nil {
		return nil
	}
	out := new(Environment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Environment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentList) DeepCopyInto(out *EnvironmentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Environment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentList.
func (in *EnvironmentList) DeepCopy() *EnvironmentList {
	if in == nil {
		return nil
	}
	out := new(EnvironmentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EnvironmentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentSpec) DeepCopyInto(out *EnvironmentSpec) {
	*out = *in
	in.EncryptionKeyRef.DeepCopyInto(&out.EncryptionKeyRef)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentSpec.
func (in *EnvironmentSpec) DeepCopy() *EnvironmentSpec {
	if in == nil {
		return nil
	}
	out := new(EnvironmentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentStatus) DeepCopyInto(out *EnvironmentStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentStatus.
func (in *EnvironmentStatus) DeepCopy() *EnvironmentStatus {
	if in == nil {
		return nil
	}
	out := new(EnvironmentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FileStoreGCSConfig) DeepCopyInto(out *FileStoreGCSConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FileStoreGCSConfig.
func (in *FileStoreGCSConfig) DeepCopy() *FileStoreGCSConfig {
	if in == nil {
		return nil
	}
	out := new(FileStoreGCSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FileStoreMinioConfig) DeepCopyInto(out *FileStoreMinioConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FileStoreMinioConfig.
func (in *FileStoreMinioConfig) DeepCopy() *FileStoreMinioConfig {
	if in == nil {
		return nil
	}
	out := new(FileStoreMinioConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FileStoreS3Config) DeepCopyInto(out *FileStoreS3Config) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FileStoreS3Config.
func (in *FileStoreS3Config) DeepCopy() *FileStoreS3Config {
	if in == nil {
		return nil
	}
	out := new(FileStoreS3Config)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HelmChartRepository) DeepCopyInto(out *HelmChartRepository) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HelmChartRepository.
func (in *HelmChartRepository) DeepCopy() *HelmChartRepository {
	if in == nil {
		return nil
	}
	out := new(HelmChartRepository)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubernetesAppStateInformer) DeepCopyInto(out *KubernetesAppStateInformer) {
	*out = *in
	if in.IncludeResources != nil {
		in, out := &in.IncludeResources, &out.IncludeResources
		*out = make([]KubernetesResourceMatcher, len(*in))
		copy(*out, *in)
	}
	if in.ExcludeResources != nil {
		in, out := &in.ExcludeResources, &out.ExcludeResources
		*out = make([]KubernetesResourceMatcher, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubernetesAppStateInformer.
func (in *KubernetesAppStateInformer) DeepCopy() *KubernetesAppStateInformer {
	if in == nil {
		return nil
	}
	out := new(KubernetesAppStateInformer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubernetesResourceMatcher) DeepCopyInto(out *KubernetesResourceMatcher) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubernetesResourceMatcher.
func (in *KubernetesResourceMatcher) DeepCopy() *KubernetesResourceMatcher {
	if in == nil {
		return nil
	}
	out := new(KubernetesResourceMatcher)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Minio) DeepCopyInto(out *Minio) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Minio.
func (in *Minio) DeepCopy() *Minio {
	if in == nil {
		return nil
	}
	out := new(Minio)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Minio) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinioList) DeepCopyInto(out *MinioList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Minio, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinioList.
func (in *MinioList) DeepCopy() *MinioList {
	if in == nil {
		return nil
	}
	out := new(MinioList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MinioList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinioSpec) DeepCopyInto(out *MinioSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Secret != nil {
		in, out := &in.Secret, &out.Secret
		*out = new(v1.SecretVolumeSource)
		(*in).DeepCopyInto(*out)
	}
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		*out = new(StorageSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinioSpec.
func (in *MinioSpec) DeepCopy() *MinioSpec {
	if in == nil {
		return nil
	}
	out := new(MinioSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinioStatus) DeepCopyInto(out *MinioStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinioStatus.
func (in *MinioStatus) DeepCopy() *MinioStatus {
	if in == nil {
		return nil
	}
	out := new(MinioStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Mongo) DeepCopyInto(out *Mongo) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Mongo.
func (in *Mongo) DeepCopy() *Mongo {
	if in == nil {
		return nil
	}
	out := new(Mongo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Mongo) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongoList) DeepCopyInto(out *MongoList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Mongo, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongoList.
func (in *MongoList) DeepCopy() *MongoList {
	if in == nil {
		return nil
	}
	out := new(MongoList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MongoList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongoSpec) DeepCopyInto(out *MongoSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		*out = new(StorageSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongoSpec.
func (in *MongoSpec) DeepCopy() *MongoSpec {
	if in == nil {
		return nil
	}
	out := new(MongoSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongoStatus) DeepCopyInto(out *MongoStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongoStatus.
func (in *MongoStatus) DeepCopy() *MongoStatus {
	if in == nil {
		return nil
	}
	out := new(MongoStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotificationReceiver) DeepCopyInto(out *NotificationReceiver) {
	*out = *in
	if in.Slack != nil {
		in, out := &in.Slack, &out.Slack
		*out = new(NotificationReceiverSlack)
		**out = **in
	}
	if in.Webhook != nil {
		in, out := &in.Webhook, &out.Webhook
		*out = new(NotificationReceiverWebhook)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotificationReceiver.
func (in *NotificationReceiver) DeepCopy() *NotificationReceiver {
	if in == nil {
		return nil
	}
	out := new(NotificationReceiver)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotificationReceiverSlack) DeepCopyInto(out *NotificationReceiverSlack) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotificationReceiverSlack.
func (in *NotificationReceiverSlack) DeepCopy() *NotificationReceiverSlack {
	if in == nil {
		return nil
	}
	out := new(NotificationReceiverSlack)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotificationReceiverWebhook) DeepCopyInto(out *NotificationReceiverWebhook) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotificationReceiverWebhook.
func (in *NotificationReceiverWebhook) DeepCopy() *NotificationReceiverWebhook {
	if in == nil {
		return nil
	}
	out := new(NotificationReceiverWebhook)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotificationRoute) DeepCopyInto(out *NotificationRoute) {
	*out = *in
	if in.Events != nil {
		in, out := &in.Events, &out.Events
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.IgnoreEvents != nil {
		in, out := &in.IgnoreEvents, &out.IgnoreEvents
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Groups != nil {
		in, out := &in.Groups, &out.Groups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.IgnoreGroups != nil {
		in, out := &in.IgnoreGroups, &out.IgnoreGroups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Apps != nil {
		in, out := &in.Apps, &out.Apps
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.IgnoreApps != nil {
		in, out := &in.IgnoreApps, &out.IgnoreApps
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Envs != nil {
		in, out := &in.Envs, &out.Envs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.IgnoreEnvs != nil {
		in, out := &in.IgnoreEnvs, &out.IgnoreEnvs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotificationRoute.
func (in *NotificationRoute) DeepCopy() *NotificationRoute {
	if in == nil {
		return nil
	}
	out := new(NotificationRoute)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Notifications) DeepCopyInto(out *Notifications) {
	*out = *in
	if in.Routes != nil {
		in, out := &in.Routes, &out.Routes
		*out = make([]NotificationRoute, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Receivers != nil {
		in, out := &in.Receivers, &out.Receivers
		*out = make([]NotificationReceiver, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Notifications.
func (in *Notifications) DeepCopy() *Notifications {
	if in == nil {
		return nil
	}
	out := new(Notifications)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Piped) DeepCopyInto(out *Piped) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Piped.
func (in *Piped) DeepCopy() *Piped {
	if in == nil {
		return nil
	}
	out := new(Piped)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Piped) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipedAnalysisProvider) DeepCopyInto(out *PipedAnalysisProvider) {
	*out = *in
	if in.PrometheusConfig != nil {
		in, out := &in.PrometheusConfig, &out.PrometheusConfig
		*out = new(AnalysisProviderPrometheusConfig)
		**out = **in
	}
	if in.DatadogConfig != nil {
		in, out := &in.DatadogConfig, &out.DatadogConfig
		*out = new(AnalysisProviderDatadogConfig)
		**out = **in
	}
	if in.StackdriverConfig != nil {
		in, out := &in.StackdriverConfig, &out.StackdriverConfig
		*out = new(AnalysisProviderStackdriverConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipedAnalysisProvider.
func (in *PipedAnalysisProvider) DeepCopy() *PipedAnalysisProvider {
	if in == nil {
		return nil
	}
	out := new(PipedAnalysisProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipedCloudProvider) DeepCopyInto(out *PipedCloudProvider) {
	*out = *in
	if in.KubernetesConfig != nil {
		in, out := &in.KubernetesConfig, &out.KubernetesConfig
		*out = new(CloudProviderKubernetesConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.TerraformConfig != nil {
		in, out := &in.TerraformConfig, &out.TerraformConfig
		*out = new(CloudProviderTerraformConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.CloudRunConfig != nil {
		in, out := &in.CloudRunConfig, &out.CloudRunConfig
		*out = new(CloudProviderCloudRunConfig)
		**out = **in
	}
	if in.LambdaConfig != nil {
		in, out := &in.LambdaConfig, &out.LambdaConfig
		*out = new(CloudProviderLambdaConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipedCloudProvider.
func (in *PipedCloudProvider) DeepCopy() *PipedCloudProvider {
	if in == nil {
		return nil
	}
	out := new(PipedCloudProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipedConfig) DeepCopyInto(out *PipedConfig) {
	*out = *in
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipedConfig.
func (in *PipedConfig) DeepCopy() *PipedConfig {
	if in == nil {
		return nil
	}
	out := new(PipedConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipedConfigSpec) DeepCopyInto(out *PipedConfigSpec) {
	*out = *in
	out.Git = in.Git
	if in.Repositories != nil {
		in, out := &in.Repositories, &out.Repositories
		*out = make([]PipedRepository, len(*in))
		copy(*out, *in)
	}
	if in.ChartRepositories != nil {
		in, out := &in.ChartRepositories, &out.ChartRepositories
		*out = make([]HelmChartRepository, len(*in))
		copy(*out, *in)
	}
	if in.CloudProviders != nil {
		in, out := &in.CloudProviders, &out.CloudProviders
		*out = make([]PipedCloudProvider, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AnalysisProviders != nil {
		in, out := &in.AnalysisProviders, &out.AnalysisProviders
		*out = make([]PipedAnalysisProvider, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Notifications.DeepCopyInto(&out.Notifications)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipedConfigSpec.
func (in *PipedConfigSpec) DeepCopy() *PipedConfigSpec {
	if in == nil {
		return nil
	}
	out := new(PipedConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipedGit) DeepCopyInto(out *PipedGit) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipedGit.
func (in *PipedGit) DeepCopy() *PipedGit {
	if in == nil {
		return nil
	}
	out := new(PipedGit)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipedList) DeepCopyInto(out *PipedList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Piped, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipedList.
func (in *PipedList) DeepCopy() *PipedList {
	if in == nil {
		return nil
	}
	out := new(PipedList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PipedList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipedRepository) DeepCopyInto(out *PipedRepository) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipedRepository.
func (in *PipedRepository) DeepCopy() *PipedRepository {
	if in == nil {
		return nil
	}
	out := new(PipedRepository)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipedSpec) DeepCopyInto(out *PipedSpec) {
	*out = *in
	in.EncryptionKeyRef.DeepCopyInto(&out.EncryptionKeyRef)
	in.Config.DeepCopyInto(&out.Config)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipedSpec.
func (in *PipedSpec) DeepCopy() *PipedSpec {
	if in == nil {
		return nil
	}
	out := new(PipedSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PipedStatus) DeepCopyInto(out *PipedStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PipedStatus.
func (in *PipedStatus) DeepCopy() *PipedStatus {
	if in == nil {
		return nil
	}
	out := new(PipedStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectStaticUser) DeepCopyInto(out *ProjectStaticUser) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectStaticUser.
func (in *ProjectStaticUser) DeepCopy() *ProjectStaticUser {
	if in == nil {
		return nil
	}
	out := new(ProjectStaticUser)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SSOConfigGitHub) DeepCopyInto(out *SSOConfigGitHub) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SSOConfigGitHub.
func (in *SSOConfigGitHub) DeepCopy() *SSOConfigGitHub {
	if in == nil {
		return nil
	}
	out := new(SSOConfigGitHub)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SSOConfigGoogle) DeepCopyInto(out *SSOConfigGoogle) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SSOConfigGoogle.
func (in *SSOConfigGoogle) DeepCopy() *SSOConfigGoogle {
	if in == nil {
		return nil
	}
	out := new(SSOConfigGoogle)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SharedSSOConfig) DeepCopyInto(out *SharedSSOConfig) {
	*out = *in
	out.GitHub = in.GitHub
	out.Google = in.Google
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SharedSSOConfig.
func (in *SharedSSOConfig) DeepCopy() *SharedSSOConfig {
	if in == nil {
		return nil
	}
	out := new(SharedSSOConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageSpec) DeepCopyInto(out *StorageSpec) {
	*out = *in
	if in.EmptyDir != nil {
		in, out := &in.EmptyDir, &out.EmptyDir
		*out = new(v1.EmptyDirVolumeSource)
		(*in).DeepCopyInto(*out)
	}
	if in.VolumeClaimTemplate != nil {
		in, out := &in.VolumeClaimTemplate, &out.VolumeClaimTemplate
		*out = new(EmbeddedPersistentVolumeClaim)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageSpec.
func (in *StorageSpec) DeepCopy() *StorageSpec {
	if in == nil {
		return nil
	}
	out := new(StorageSpec)
	in.DeepCopyInto(out)
	return out
}
